### ISSUE TITLE
Season 5 Connections

### ISSUE THREAD

**Issue by B-Lemke** [anGie44/theOffice-api#1]
Hi! 

I'm making a daily executing script that sends out a random office quote via email to friends, and I was having issues with accessing the connections for season 5 via this URL: https://the-office-api.herokuapp.com/season/5/format/connections

**Comment by gabrieltriggs** [comment]
I'm in the same boat! Seems like there's something minor going wrong with the response when you request season 5. Hoping you can possibly take a look at it. Thanks!

**Comment by gabrieltriggs** [comment]
Okay so I figured out what's up. The reason this is specifically affecting season 5 is that season 5 is the only season containing any episodes with titles not placed in quotation marks - episodes 14 & 15 have their quotation marks omitted for no apparent reason. So the regex that is used to grab the episode title is expecting it to be in quotation marks and blowing up when it fails to encounter those quotation marks. The only thing I would know to do to fix this would be to add a conditional before the regex is used to grab the title and specifically provide the title manually for those two episodes.

All that said, I'm just gonna contact officequotes.net and ask that they fix those two episode titles, which should immediately resolve this problem.

**Comment by anGie44** [comment]
@B-Lemke @gabrieltriggs thanks so much for the input guys! i'm working on a graphql implementation of this api to make querying easier and persist data on the backend in some form of data store/cache. it's still a work-in-progress but i'll keep in mind the snags you've across with the season 5 data 😃

**Comment by anGie44** [comment]
Hi all 👋 It's been a while but I had a chance to update the API and this should be fixed with https://github.com/anGie44/theOffice-api/pull/3 . Thanks again for the initial feedback
