### ISSUE TITLE
Will API work again?

### ISSUE THREAD

**Issue by elysenewland** [anGie44/theOffice-api#5]
I see in the README file that the heroku app is down. Is there a plan to get this API working again? Thanks!

**Comment by AkshayHere** [comment]
@anGie44 Can you try maybe re-deploying this in netlify or something instead of heroku ?

**Comment by anGie44** [comment]
I re-deployed with `back4app` so it should be live @ https://theofficeapi-angelinepinilla.b4a.run for the time being 😄 thanks for using it ❤️
